#!/usr/bin/env node

import console from "node:console";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// repo-root/config/version.json (relative to this script)
const versionConfig = path.resolve(__dirname, "..", "config", "version.json");

// Where we write the generated TS module
const outDir = path.resolve(__dirname, "..", "src", "__generated");
const outFile = path.join(outDir, "version.ts");

// Read version.json
let raw;
try {
  raw = fs.readFileSync(versionConfig, "utf8");
} catch {
  console.error(
    `Could not read ${versionConfig}. Make sure config/version.json exists.`,
  );
  process.exit(1);
}

let data;
try {
  data = JSON.parse(raw);
} catch (e) {
  console.error(`Failed to parse ${versionConfig}: ${e.message}`);
  process.exit(1);
}

// Accepts { "lsp-version": "0.x.y" }
const lspVersion = data["lsp-version"];
if (!lspVersion || typeof lspVersion !== "string") {
  console.error(
    `Expected "lsp-version" in ${versionConfig}, got: ` + JSON.stringify(data),
  );
  process.exit(1);
}

const containerRegistry = data["container-registry"];
if (!containerRegistry || typeof containerRegistry !== "string") {
  console.error(
    `Expected "container-registry" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

const languageImageVersion = data["language-image-version"];
if (!languageImageVersion || typeof languageImageVersion !== "string") {
  console.error(
    `Expected "language-image-version" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

const serviceImageVersion = data["service-image-version"];
if (!serviceImageVersion || typeof serviceImageVersion !== "string") {
  console.error(
    `Expected "service-image-version" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

// Ensure output dir exists
fs.mkdirSync(outDir, { recursive: true });

// Emit TypeScript module (formatted to pass Prettier)
const contents = `// AUTO-GENERATED FILE. Do not edit.
// Generated by scripts/generate-version.mjs

export const VERSION = ${JSON.stringify(lspVersion)};

export const CONTAINER_REGISTRY = ${JSON.stringify(containerRegistry)};
export const LANGUAGE_IMAGE_VERSION = ${JSON.stringify(languageImageVersion)};
export const SERVICE_IMAGE_VERSION = ${JSON.stringify(serviceImageVersion)};
`;
fs.writeFileSync(outFile, contents, "utf8");

console.log(`Generated ${path.relative(process.cwd(), outFile)}`);

// Update package.json version
const pkgJsonPath = path.resolve(__dirname, "..", "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"));

pkg.version = lspVersion; // overwrite version field

fs.writeFileSync(pkgJsonPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
console.log(
  `Updated ${path.relative(process.cwd(), pkgJsonPath)} version to ${lspVersion}`,
);
