#!/usr/bin/env node

import console from "node:console";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// repo-root/package.json (relative to this script)
const pkgJson = path.resolve(__dirname, "..", "package.json");

// Where we write the generated TS module
const outDir = path.resolve(__dirname, "..", "src", "__generated");
const outFile = path.join(outDir, "version.ts");

// Read package.json
const pkg = JSON.parse(fs.readFileSync(pkgJson, "utf8"));

// Ensure output dir exists
fs.mkdirSync(outDir, { recursive: true });

// Emit TypeScript module (formatted to pass Prettier)
const contents = `// AUTO-GENERATED FILE. Do not edit.
// Generated by scripts/generate-version.mjs
export const VERSION = ${JSON.stringify(pkg.version)};
`;
fs.writeFileSync(outFile, contents, "utf8");

console.log(`Generated ${path.relative(process.cwd(), outFile)}`);
