#!/usr/bin/env node

import console from "node:console";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// repo-root/config/version.json (relative to this script)
const versionConfig = path.resolve(__dirname, "..", "config", "version.json");

// Where we write the generated TS module
const outDir = path.resolve(__dirname, "..", "src", "__generated");
const outFile = path.join(outDir, "version.ts");

// Read version.json
let raw;
try {
  raw = fs.readFileSync(versionConfig, "utf8");
} catch {
  console.error(
    `Could not read ${versionConfig}. Make sure config/version.json exists.`,
  );
  process.exit(1);
}

let data;
try {
  data = JSON.parse(raw);
} catch (e) {
  console.error(`Failed to parse ${versionConfig}: ${e.message}`);
  process.exit(1);
}

// Accepts { "lsp-version": "0.x.y" }
const lspVersion = data["lsp-version"];
if (!lspVersion || typeof lspVersion !== "string") {
  console.error(
    `Expected "lsp-version" in ${versionConfig}, got: ` + JSON.stringify(data),
  );
  process.exit(1);
}

const nuancedLSPProxyVersion = data["lsp-proxy-version"];
if (!nuancedLSPProxyVersion || typeof nuancedLSPProxyVersion !== "string") {
  console.error(
    `Expected "lsp-proxy-version" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

const nuancedLSPWrapperVersion = data["lsp-wrapper-version"];
if (!nuancedLSPWrapperVersion || typeof nuancedLSPWrapperVersion !== "string") {
  console.error(
    `Expected "lsp-wrapper-version" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

const nuancedLSPWatchdogVersion = data["lsp-watchdog-version"];
if (
  !nuancedLSPWatchdogVersion ||
  typeof nuancedLSPWatchdogVersion !== "string"
) {
  console.error(
    `Expected "lsp-watchdog-version" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

const languageContainerVersion = data["language-container-version"];
if (!languageContainerVersion || typeof languageContainerVersion !== "string") {
  console.error(
    `Expected "language-container-version" in ${versionConfig}, got: ` +
      JSON.stringify(data),
  );
  process.exit(1);
}

// Image base is fixed per your requirement
const PROXY_IMAGE_BASE = "ghcr.io/nuanced-dev/nuanced-lsp-proxy";
const DEFAULT_PROXY_IMAGE = `${PROXY_IMAGE_BASE}:${nuancedLSPProxyVersion}`;

const WRAPPER_IMAGE_BASE = "ghcr.io/nuanced-dev/nuanced-lsp-wrapper";
const DEFAULT_WRAPPER_IMAGE = `${WRAPPER_IMAGE_BASE}:${nuancedLSPProxyVersion}`;

const WATCHDOG_IMAGE_BASE = "ghcr.io/nuanced-dev/nuanced-lsp-watchdog";
const DEFAULT_WATCHDOG_IMAGE = `${WATCHDOG_IMAGE_BASE}:${nuancedLSPWatchdogVersion}`;

// Ensure output dir exists
fs.mkdirSync(outDir, { recursive: true });

// Emit TypeScript module (formatted to pass Prettier)
const contents = `/* eslint-ignore */
/* tslint-ignore */
// AUTO-GENERATED FILE. Do not edit.
// Generated by script/generate-version.mjs
export const DEFAULT_PROXY_IMAGE =
  ${JSON.stringify(DEFAULT_PROXY_IMAGE)};
export const DEFAULT_WRAPPER_IMAGE =
  ${JSON.stringify(DEFAULT_WRAPPER_IMAGE)};
export const DEFAULT_WATCHDOG_IMAGE =
  ${JSON.stringify(DEFAULT_WATCHDOG_IMAGE)};
export const VERSION = ${JSON.stringify(lspVersion)};
export const LANGUAGE_IMAGE_VERSION = ${JSON.stringify(languageContainerVersion)};
`;
fs.writeFileSync(outFile, contents, "utf8");

console.log(`Generated ${path.relative(process.cwd(), outFile)}`);

// Update package.json version
const pkgJsonPath = path.resolve(__dirname, "..", "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"));

pkg.version = lspVersion; // overwrite version field

fs.writeFileSync(pkgJsonPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
console.log(
  `Updated ${path.relative(process.cwd(), pkgJsonPath)} version to ${lspVersion}`,
);
