// AUTO-GENERATED FILE. Do not edit.
// Generated by scripts/generate-version.mjs
export const VERSION = "0.4.0";
export const LANGUAGE_IMAGE_VERSION = "1.0.0";
export const SERVICE_IMAGE_VERSION = "0.4.9";
export const CONTAINER_REGISTRY = "ghcr.io/nuanced-dev";
