// AUTO-GENERATED FILE. Do not edit.
// Generated by script/generate-version.mjs
export const DEFAULT_PROXY_IMAGE =
  "ghcr.io/nuanced-dev/nuanced-lsp-proxy:0.4.9";
export const DEFAULT_WRAPPER_IMAGE =
  "ghcr.io/nuanced-dev/nuanced-lsp-wrapper:0.4.9";
export const DEFAULT_WATCHDOG_IMAGE =
  "ghcr.io/nuanced-dev/nuanced-lsp-watchdog:0.4.9";
export const VERSION = "0.4.0";
export const LANGUAGE_IMAGE_VERSION = "1.0.0";
