name: TypeScript Tests

on:
  push:
    branches:
    - main
    paths:
    - 'clients/typescript/**'
  pull_request:
    paths:
    - 'clients/typescript/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    working-directory: clients/typescript

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [24.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
      env:
        NUANCED_LSP_TIMEOUT: 240
        FAIL_FAST: 1
